# Data Cleaning & Preprocessing

## Objective

The objective of this notebook is to clean the dataset and prepare it for exploratory data analysis and machine learning. This includes handling incorrect data types, detecting hidden missing values, removing unnecessary features, and preventing data leakage.

# Import Libraries

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

# Load the Dataset

In [2]:
df = pd.read_excel(r"..\data\raw_data.xlsx")

df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.96,-118.27,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.06,-118.31,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.05,-118.29,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.06,-118.32,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.04,-118.27,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

# Create a Copy of the Dataset

In [3]:
cleaned_df = df.copy()

# Dataset Information

In [4]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

# Missing Values

In [5]:
(cleaned_df == " ").sum().sort_values(ascending=False)

Total Charges        11
CustomerID            0
Count                 0
State                 0
Country               0
Zip Code              0
Lat Long              0
Latitude              0
City                  0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Longitude             0
Internet Service      0
Online Security       0
Device Protection     0
Online Backup         0
Streaming TV          0
Streaming Movies      0
Contract              0
Tech Support          0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Churn Label           0
Churn Value           0
Churn Score           0
CLTV                  0
Churn Reason          0
dtype: int64

## Replace Blank Spaces with Missing Values

In [6]:
cleaned_df = cleaned_df.replace(" ", np.nan)

## Missing Values After Replacement

In [7]:
cleaned_df.isnull().sum().sort_values(ascending=False)

Churn Reason         5174
Total Charges          11
CustomerID              0
Count                   0
Country                 0
Zip Code                0
Lat Long                0
State                   0
City                    0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Latitude                0
Longitude               0
Internet Service        0
Multiple Lines          0
Online Security         0
Online Backup           0
Streaming TV            0
Streaming Movies        0
Device Protection       0
Tech Support            0
Paperless Billing       0
Contract                0
Monthly Charges         0
Payment Method          0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
dtype: int64

# Data Types

In [8]:
cleaned_df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

# Data Types

In [9]:
cleaned_df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

## Convert Total Charges to Numeric

In [10]:
cleaned_df["Total Charges"] = pd.to_numeric(
    cleaned_df["Total Charges"],
    errors="coerce"
)

In [11]:
cleaned_df["Total Charges"].dtype

dtype('float64')

# Missing Values Summary

In [12]:
missing = pd.DataFrame({
    "Missing": cleaned_df.isnull().sum(),
    "Percentage": cleaned_df.isnull().mean() * 100
})

missing[missing["Missing"] > 0]

               Missing  Percentage
Total Charges       11        0.16
Churn Reason      5174       73.46

In [13]:
cleaned_df.loc[
    cleaned_df["Total Charges"].isnull(),
    ["Tenure Months", "Monthly Charges", "Total Charges"]
]

      Tenure Months  Monthly Charges  Total Charges
2234              0            52.55            NaN
2438              0            20.25            NaN
2568              0            80.85            NaN
2667              0            25.75            NaN
2856              0            56.05            NaN
4331              0            19.85            NaN
4687              0            25.35            NaN
5104              0            20.00            NaN
5719              0            19.70            NaN
6772              0            73.35            NaN
6840              0            61.90            NaN

In [14]:
cleaned_df = cleaned_df.dropna(subset=["Total Charges"])

In [17]:
cleaned_df.isnull().sum().sum()

np.int64(5163)

In [18]:
missing = cleaned_df.isnull().sum()

missing[missing > 0]

Churn Reason    5163
dtype: int64

## Missing Values Analysis

The dataset contains missing values only in the **Churn Reason** feature.

This is expected because the reason for churn is only available for customers who have already left the company. Customers who did not churn do not have a churn reason.

Therefore, these missing values do not represent data quality issues.

# Data Leakage Analysis

## Identifying Features That Should Not Be Used for Model Training

In [19]:
feature_decision = pd.DataFrame({
    "Feature": cleaned_df.columns
})

feature_decision

              Feature
0          CustomerID
1               Count
2             Country
3               State
4                City
5            Zip Code
6            Lat Long
7            Latitude
8           Longitude
9              Gender
10     Senior Citizen
11            Partner
12         Dependents
13      Tenure Months
14      Phone Service
15     Multiple Lines
16   Internet Service
17    Online Security
18      Online Backup
19  Device Protection
20       Tech Support
21       Streaming TV
22   Streaming Movies
23           Contract
24  Paperless Billing
25     Payment Method
26    Monthly Charges
27      Total Charges
28        Churn Label
29        Churn Value
30        Churn Score
31               CLTV
32       Churn Reason

### CustomerID

### Count

### Country

### Churn Label

### Churn Score

### Churn Reason

### CLTV

In [24]:
columns_to_drop = [
    "CustomerID",
    "Count",
    "Country",
    "Churn Label",
    "Churn Score",
    "CLTV",
    "Churn Reason"
]

cleaned_df = cleaned_df.drop(columns=columns_to_drop)

# Verify the Cleaned Dataset

In [25]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              7032 non-null   object
 1   City               7032 non-null   object
 2   Zip Code           7032 non-null   int64
 3   Lat Long           7032 non-null   object
 4   Latitude           7032 non-null   float64
 5   Longitude          7032 non-null   float64
 6   Gender             7032 non-null   object
 7   Senior Citizen     7032 non-null   object
 8   Partner            7032 non-null   object
 9   Dependents         7032 non-null   object
 10  Tenure Months      7032 non-null   int64
 11  Phone Service      7032 non-null   object
 12  Multiple Lines     7032 non-null   object
 13  Internet Service   7032 non-null   object
 14  Online Security    7032 non-null   object
 15  Online Backup      7032 non-null   object
 16  Device Protection  7032 non-null   object
 17  Tech Support       7032 non-null   object
 18  Streaming TV       7032 non-null   object
 19  Streaming Movies   7032 non-null   object
 20  Contract           7032 non-null   object
 21  Paperless Billing  7032 non-null   object
 22  Payment Method     7032 non-null   object
 23  Monthly Charges    7032 non-null   float64
 24  Total Charges      7032 non-null   float64
 25  Churn Value        7032 non-null   int64
dtypes: float64(4), int64(3), object(19)
memory usage: 1.4+ MB

In [28]:
cleaned_df.head()

,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
0,California,Los Angeles,90003,"33.964131, -118.272783",33.96,-118.27,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,California,Los Angeles,90005,"34.059281, -118.30742",34.06,-118.31,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,California,Los Angeles,90006,"34.048013, -118.293953",34.05,-118.29,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1
3,California,Los Angeles,90010,"34.062125, -118.315709",34.06,-118.32,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
4,California,Los Angeles,90015,"34.039224, -118.266293",34.04,-118.27,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1

In [29]:

print(cleaned_df.shape)

(7032, 26)

# Save the Cleaned Dataset

In [30]:
cleaned_df.to_csv(
    "../data/processed_data.csv",
    index=False
)